disabled_rules:
  - line_length
  - trailing_whitespace
  - function_parameter_count

excluded:
  - Pods
  - Carthage
  - .git
  - build
  - Tymofieiev_Danylo_abz.agency/Generated
  - Tymofieiev_Danylo_abz.agencyTests
  - Tymofieiev_Danylo_abz.agencyUITests

type_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
